{% set version = "6.5.5" %}
# {% set commit = "3814f0097ca199d43ade2e25654c37abab0f7a9b" %}

package:
  name: ogs
  version: {{ version }}

source:
  url: https://github.com/ufz/ogs/archive/refs/tags/{{ version }}.tar.gz
  # url: https://gitlab.opengeosys.org/ogs/ogs/-/archive/{{ commit }}/ogs-{{ commit }}.tar.gz
  sha256: 675a58e00b98d29c7ab9076ce0292aa8a728cb0902760e52ae26e53164ef9e1e

build:
  number: 2
  skip: true  # [win]
  ignore_run_exports:
    - libboost-python
    - exprtk
    - metis
    - libzlib

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - libgomp                                # [linux]
    - llvm-openmp                            # [osx]
    - make                                   # [linux]
    - tbb-devel
  host:
    - eigen
    - exprtk
    - hdf5
    - libboost-python-devel               # [not osx]
    - libboost-python-devel >=1.88.0      # [osx]
    - libxml2
    - metis
    - nlohmann_json
    - pybind11
    - python
    - range-v3
    - tclap
    - vtk >=9.3.0                          # [not osx]
    - vtk >=9.5.0                          # [osx]
    - zlib
    - mfront 4.2                           # [linux]
    - mgis 2.2                             # [linux]
  run:
    - tetgen
    - python
    - mfront 4.2                           # [linux]
    - mgis 2.2                             # [linux]
    - tbb

test:
  commands:
    - ogs --version

about:
  home: http://www.opengeosys.org/
  summary: OpenGeoSys (OGS) THMC simulator.
  description: |
    OpenGeoSys (OGS) is a scientific open source project for the development
    of numerical methods for the simulation of thermo-hydro-mechanical-
    chemical (THMC) processes in porous and fractured media. 
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - scripts/cmake/json-cmake/LICENSE
    - build/third_party_licenses.txt
  doc_url: https://www.opengeosys.org/docs
  dev_url: https://gitlab.opengeosys.org/ogs/ogs

extra:
  recipe-maintainers:
    - bilke
